name: WhiteSource CI integration
on:
  push:
    branches: [ develop, release, master ]

jobs:
  WhiteSource:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
     - name: WhiteSource CI integration
       uses: Idancc/WhiteSource-CI-Integration@v2.6
